# Generated by Django 4.1.2 on 2022-10-25 13:19

import Recipies.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=250, validators=[Recipies.web.models.contain_coma]),
        ),
    ]
