# Generated by Django 4.1.3 on 2022-11-09 13:23

import UsersDemos.auth_app.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_appuser_groups_appuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', UsersDemos.auth_app.managers.AppUserManager()),
            ],
        ),
    ]
