# Generated by Django 4.1.3 on 2022-11-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_staff',
        ),
    ]
